### ISSUE TITLE
Exception: Strategy SimpleStrategy not found on optimize modes simple strategy

### ISSUE THREAD

**Issue by bjornm82** [happydasch/btconfig#15]
While running the simple demo, **run_backtest.py** works fine, but both **run_optimize.py** and **run_optimizegenetic.py** runs into a similar issue, Exception: Strategy SimpleStrategy not found.

I fail to understand why this would occurs, the lines of code is around **strategy.py** where in all cases the exact same information is being dispatched:

```
        stratname = commoncfg.get('strategy', None)
        all_classes = get_classes(self._instance.PATH_STRATEGY)
        if stratname not in all_classes:
            raise Exception(f'Strategy {stratname} not found')
```
stratname = SimpleStrategy
all_classes = {'SimpleStrategy': <class 'simple_strategy.SimpleStrategy'>}
, but in both optimize modes there it will raise the error below:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/bjornmooijekind/Projects/btconfig/demo/simple/run_optimize.py", line 4, in <module>
    res = btconfig.run(btconfig.MODE_OPTIMIZE, "config.json")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/btconfig-0.2.5-py3.8.egg/btconfig/__init__.py", line 776, in run
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/btconfig-0.2.5-py3.8.egg/btconfig/__init__.py", line 512, in run
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/btconfig-0.2.5-py3.8.egg/btconfig/__init__.py", line 461, in _setup
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/btconfig-0.2.5-py3.8.egg/btconfig/parts/strategy.py", line 64, in setup
Exception: Strategy SimpleStrategy not found
```

**Comment by happydasch** [comment]
thanks for reporting and i can reproduce it. will look into that but it seems, this has something to do with threads.

**Comment by happydasch** [comment]
the missing class happens, when trying to access the imports from main, when in a new process. so i added the needed module to search paths for strategies.

but there was also another issue with starting optimization from within a optimization process which is also fixed.

**Comment by bjornm82** [comment]
Sweet! Thanks very much! 👍 Working like expected right now.
