### ISSUE TITLE
cant import btconfig in python shell

### ISSUE THREAD

**Issue by DjangodevArif** [happydasch/btconfig#9]
First of all i don't know too much regarding this module . When i try to run the demo/simple file for understand better but it's showing " no module found  named btconfig ' . That's why i try to import btconfig into my python shell it's showing this error.
 ```
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import btconfig
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/arif/Main/Programs/R_&_D/Python/btconfig/btconfig/__init__.py", line 258, in <module>
    import backtrader as bt
  File "/home/arif/Main/Programs/R_&_D/Python/btconfig/env/lib/python3.8/site-packages/backtrader/__init__.py", line 62, in <module>
    from .cerebro import *
  File "/home/arif/Main/Programs/R_&_D/Python/btconfig/env/lib/python3.8/site-packages/backtrader/cerebro.py", line 35, in <module>
    from .brokers import BackBroker
  File "/home/arif/Main/Programs/R_&_D/Python/btconfig/env/lib/python3.8/site-packages/backtrader/brokers/__init__.py", line 30, in <module>
    from .ibbroker import IBBroker
  File "/home/arif/Main/Programs/R_&_D/Python/btconfig/env/lib/python3.8/site-packages/backtrader/brokers/ibbroker.py", line 30, in <module>
    import ib.ext.Order
  File "/home/arif/Main/Programs/R_&_D/Python/btconfig/env/lib/python3.8/site-packages/ib/ext/Order.py", line 9, in <module>
    from ib.lib import Double, Integer
  File "/home/arif/Main/Programs/R_&_D/Python/btconfig/env/lib/python3.8/site-packages/ib/lib/__init__.py", line 239
    except (socket.error, ), ex:
                           ^
SyntaxError: invalid syntax
```

**Comment by happydasch** [comment]
you have some syntax error in the ib package, not a btconfig issue

```
 File "/home/arif/Main/Programs/R_&_D/Python/btconfig/env/lib/python3.8/site-packages/ib/lib/__init__.py", line 239
   except (socket.error, ), ex:

```
